spring.application.name=fraud-detection

# Kafka Configuration
spring.kafka.bootstrap-servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';

#kafka group ids
spring.kafka.consumer.group-id=fraud-detection-group

# kafka topics
spring.kafka.consumer.topic-trEvents=payment-transaction-events
spring.kafka.producer.topic=fraud-alerts

# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Snowflake
snowflake.account=${SNOWFLAKE_ACCOUNT}
snowflake.user=${SNOWFLAKE_USER}
snowflake.password=${SNOWFLAKE_PASSWORD}
snowflake.warehouse=${SNOWFLAKE_WAREHOUSE}
snowflake.database=${SNOWFLAKE_DATABASE}
snowflake.schema=${SNOWFLAKE_SCHEMA}